version: '3.9'

services:
  db:
    image: postgres:14
    container_name: pg_searchconsole
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: searchconsole
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3-management
    container_name: mq_searchconsole
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - backend

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_searchconsole
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    depends_on:
      - db
      - rabbitmq
    networks:
      - backend
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  pgdata:

networks:
  backend:
